
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false

  kafka:
    bootstrap-servers: host.docker.internal:29092
    consumer:
      group-id: message-service-group

app:
  jwt:
    secret: I26tXMOZepPHyd_fDTxirlfk60dgL_P0XB8D0qhY4jI

kafka:
  topics:
    message_1: message

